
baseURL = "/"
languageCode = "en-us"
title = "Aditya Khandkar"
paginate = 50

[taxonomies]
tag = "tags"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
style = "friendly"
noClasses = false
